/* Generated by the Nim Compiler v2.2.8 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI922747294 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555872 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555187 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555184 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI771751939 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI771751940 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI771751940 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI771751939, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI771751939, name: "a1", sons: null}]};
NTI771751940.node = NNI771751940;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
var NNI33555184 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555184.node = NNI33555184;
NTI33555186.base = NTI33555183;
NTI33555187.base = NTI33555183;
var NNI33555183 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555186, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555187, name: "up", sons: null}]};
NTI33555183.node = NNI33555183;
var NNI33555179 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555179.node = NNI33555179;
NTI33555183.base = NTI33555179;
NTI33555184.base = NTI33555183;
NTI134217751.base = NTI33555184;
var NNI33555872 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555872.node = NNI33555872;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555184;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555184;
NTI134217743.base = NTI134217741;
NTI922747294.base = NTI33554449;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555184;
var DefaultRandSeed_771751950 = {a0: 7616934476015405061n, a1: 15122295919272093642n};

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557360 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2908(ti_p2))) {
      result_33557360 = src_p1;
      }
      else {
        result_33557360 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557360 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557360 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557360 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557360 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557360, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557360 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557360 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557360 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557360[i] = nimCopy(result_33557360[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557360 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557360 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557360[i] = nimCopy(result_33557360[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557360 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557360 = src_p1;
      break;
    }

  return result_33557360;

}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557473 = false;

  BeforeRet: {
    var x_33557474 = obj_p0;
    if ((x_33557474 == subclass_p1)) {
    result_33557473 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557474 == subclass_p1))) break Label2;
          if ((x_33557474 == null)) {
          result_33557473 = false;
          break BeforeRet;
          }
          
          x_33557474 = x_33557474.base;
        }
    };
    result_33557473 = true;
    break BeforeRet;
  };

  return result_33557473;

}

function toJSStr(s_p0) {
  var result_33556949 = null;

    var res_33557003 = newSeq__system_u2546((s_p0).length);
    var i_33557004 = 0;
    var j_33557005 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33557004 < (s_p0).length)) break Label2;
          var c_33557006 = s_p0[i_33557004];
          if ((c_33557006 < 128)) {
          res_33557003[j_33557005] = String.fromCharCode(c_33557006);
          i_33557004 += 1;
          }
          else {
            var helper_33557032 = newSeq__system_u2546(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557033 = c_33557006.toString(16);
                  if ((((code_33557033) == null ? 0 : (code_33557033).length) == 1)) {
                  helper_33557032.push("%0");;
                  }
                  else {
                  helper_33557032.push("%");;
                  }
                  
                  helper_33557032.push(code_33557033);;
                  i_33557004 += 1;
                  if ((((s_p0).length <= i_33557004) || (s_p0[i_33557004] < 128))) {
                  break Label3;
                  }
                  
                  c_33557006 = s_p0[i_33557004];
                }
            };
++excHandler;
            try {
            res_33557003[j_33557005] = decodeURIComponent(helper_33557032.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33557003[j_33557005] = helper_33557032.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33557005 += 1;
        }
    };
    if (res_33557003.length < j_33557005) { for (var i = res_33557003.length ; i < j_33557005 ; ++i) res_33557003.push(null); }
               else { res_33557003.length = j_33557005; };
    result_33556949 = res_33557003.join("");

  return result_33556949;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2210(), NTI33554449);
    throw e_p0;

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557400 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557400 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557400;

}
                      var helper_771751983 = new BigUint64Array([13739361407582206667n, 15594563132006766882n]);

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557395 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557395 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557395;

}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557187 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557187 = Temporary1;
    break BeforeRet;
  };

  return result_33557187;

}

function nimMin(a_p0, b_p1) {
    var Temporary1;

  var result_33557183 = 0;

  BeforeRet: {
    if ((a_p0 <= b_p1)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557183 = Temporary1;
    break BeforeRet;
  };

  return result_33557183;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}

function nimCharToStr(x_p0) {
  var result_33556474 = [];

    result_33556474 = nimCopy(null, mnewString(1), NTI33554449);
    result_33556474[0] = x_p0;

  return result_33556474;

}

function addChar(x_p0, c_p1) {
    x_p0.push(c_p1);

  
}
var F = {procname: "module algorithm", prev: framePtr, filename: "/usr/lib/nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/usr/lib/nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/usr/lib/nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/usr/lib/nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/usr/lib/nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/usr/lib/nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/usr/lib/nim/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/usr/lib/nim/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/usr/lib/nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/usr/lib/nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/usr/lib/nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/usr/lib/nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/usr/lib/nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/usr/lib/nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/usr/lib/nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/usr/lib/nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/usr/lib/nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/usr/lib/nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/usr/lib/nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/usr/lib/nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/usr/lib/nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/usr/lib/nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/usr/lib/nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/usr/lib/nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/usr/lib/nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/usr/lib/nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/usr/lib/nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/usr/lib/nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/usr/lib/nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/usr/lib/nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/usr/lib/nim/lib/pure/times.nim", line: 0};
framePtr = F;
F.line = 1373;
F.filename = "times.nim";
if (globalThis.utcInstance_905971457 === undefined) {
  globalThis.utcInstance_905971457 = [null];
}
F.line = 1374;
if (globalThis.localInstance_905971458 === undefined) {
  globalThis.localInstance_905971458 = [null];
}
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/usr/lib/nim/lib/pure/times.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer__system_u2908(ti_p0) {
  var result_33557342 = false;

  BeforeRet: {
    result_33557342 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557342;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}
var F = {procname: "module random", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
framePtr = F;
F.line = 116;
F.filename = "random.nim";
var state_771751951 = [nimCopy(null, DefaultRandSeed_771751950, NTI771751940)];
framePtr = F.prev;
var F = {procname: "module random", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sequtils", prev: framePtr, filename: "/usr/lib/nim/lib/pure/collections/sequtils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sequtils", prev: framePtr, filename: "/usr/lib/nim/lib/pure/collections/sequtils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/usr/lib/nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 219;
F.filename = "hashes.nim";
var objectID_1090519218 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/usr/lib/nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/usr/lib/nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/usr/lib/nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sets", prev: framePtr, filename: "/usr/lib/nim/lib/pure/collections/sets.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sets", prev: framePtr, filename: "/usr/lib/nim/lib/pure/collections/sets.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/usr/lib/nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/usr/lib/nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function toFloat__system_u1596(i_p0) {
  var result_33556030 = 0.0;

  var F = {procname: "system.toFloat", prev: framePtr, filename: "/usr/lib/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1302;
    F.filename = "system.nim";
    result_33556030 = i_p0;
  framePtr = F.prev;

  return result_33556030;

}

function HEX2F__system_u1608(x_p0, y_p1) {
  var result_33556043 = 0.0;

  var F = {procname: "system./", prev: framePtr, filename: "/usr/lib/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1350;
    F.filename = "system.nim";
    result_33556043 = (toFloat__system_u1596(x_p0) / toFloat__system_u1596(y_p1));
  framePtr = F.prev;

  return result_33556043;

}

function epochTime__pureZtimes_u4708() {
  var result_905974373 = 0.0;

  var F = {procname: "times.epochTime", prev: framePtr, filename: "/usr/lib/nim/lib/pure/times.nim", line: 0};
  framePtr = F;
    F.line = 2799;
    F.filename = "times.nim";
    result_905974373 = HEX2F__system_u1608(new Date().getTime(), 1000);
  framePtr = F.prev;

  return result_905974373;

}

function add__system_u1972(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544528 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544528 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544542 = 0;
      var i_687867669 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_687867669 < n_p3)) break Label4;
            iHEX60gensym4_335544542 = i_687867669;
            result_p0[result_p0_Idx][(old_335544528 + iHEX60gensym4_335544542)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544542));
            i_687867669 += 1;
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/usr/lib/nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_385875984[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_385875984[0];

}

function auxWriteStackTrace__system_u2112(f_p0) {
  var result_33556546 = [[]];

    var it_33556554 = f_p0;
    var i_33556555 = 0;
    var total_33556556 = 0;
    var tempFrames_33556557 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555872);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556554 == null)) && (i_33556555 <= 63))) break Label2;
          tempFrames_33556557[i_33556555].Field0 = it_33556554.procname;
          tempFrames_33556557[i_33556555].Field1 = it_33556554.line;
          tempFrames_33556557[i_33556555].Field2 = it_33556554.filename;
          i_33556555 += 1;
          total_33556556 += 1;
          it_33556554 = it_33556554.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556554 == null))) break Label4;
          total_33556556 += 1;
          it_33556554 = it_33556554.prev;
        }
    };
    result_33556546[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556556 == i_33556555))) {
    nimAddStrStr(result_33556546[0], [40]);;
    nimAddStrStr(result_33556546[0], HEX24__systemZdollars_u14((total_33556556 - i_33556555)));;
    nimAddStrStr(result_33556546[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556590 = 0;
      var colontmp__687867661 = 0;
      colontmp__687867661 = (i_33556555 - 1);
      var res_687867663 = colontmp__687867661;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_687867663)) break Label7;
            j_33556590 = res_687867663;
            nimAddStrStr(result_33556546[0], cstrToNimstr(tempFrames_33556557[j_33556590].Field2));;
            if ((0 < tempFrames_33556557[j_33556590].Field1)) {
            nimAddStrStr(result_33556546[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556546, 0, tempFrames_33556557[j_33556590].Field1);
            if (false) {
            nimAddStrStr(result_33556546[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556546, 0, 0);
            }
            
            nimAddStrStr(result_33556546[0], [41]);;
            }
            
            nimAddStrStr(result_33556546[0], [32,97,116,32]);;
            add__system_u1972(result_33556546, 0, tempFrames_33556557[j_33556590].Field0);
            nimAddStrStr(result_33556546[0], [10]);;
            res_687867663 -= 1;
          }
      };
    };

  return result_33556546[0];

}

function rawWriteStackTrace__system_u2210() {
  var result_33556643 = [];

    if (!((framePtr == null))) {
    result_33556643 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2112(framePtr)), NTI33554449);
    }
    else {
      result_33556643 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556643;

}

function newSeq__system_u2546(len_p0) {
  var result_33556982 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/usr/lib/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556982 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556982[i] = null; }  framePtr = F.prev;

  return result_33556982;

}

function isNimException__system_u2043() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556478 = null;

    if (isNimException__system_u2043()) {
    result_33556478 = lastJSError;
    }
    

  return result_33556478;

}

function raiseDefect() {
    if (isNimException__system_u2043()) {
    var e_33556694 = getCurrentException();
    if (isObj(e_33556694.m_type, NTI33555184)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556694);
    }
    
    e_33556694.trace = nimCopy(null, rawWriteStackTrace__system_u2210(), NTI33554449);
    throw e_33556694;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556688 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556688[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556688[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556688[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556688[0], [32,91]);;
    add__system_u1972(buf_33556688, 0, e_p0.name);
    nimAddStrStr(buf_33556688[0], [93,10]);;
    nimAddStrStr(buf_33556688[0], rawWriteStackTrace__system_u2210());;
    var cbuf_33556689 = toJSStr(buf_33556688[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556689);
  }
  else {
    throw cbuf_33556689;
  }
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function rotl__pureZrandom_u24(x_p0, k_p1) {
  var result_771751963 = 0n;

  var F = {procname: "random.rotl", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
  framePtr = F;
    F.line = 136;
    F.filename = "random.nim";
    result_771751963 = (BigInt.asUintN(64, x_p0 << (BigInt(k_p1) & 63n)) | (x_p0 >> (BigInt(BigInt.asUintN(64, (64n - k_p1))) & 63n)));
  framePtr = F.prev;

  return result_771751963;

}

function next__pureZrandom_u36(r_p0) {
  var result_771751974 = 0n;

  var F = {procname: "random.next", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
  framePtr = F;
    F.line = 154;
    F.filename = "random.nim";
    var s0_771751975 = r_p0.a0;
    F.line = 155;
    var s1_771751976 = r_p0.a1;
    F.line = 156;
    result_771751974 = BigInt.asUintN(64, (s0_771751975 + s1_771751976));
    F.line = 157;
    s1_771751976 = (s1_771751976 ^ s0_771751975);
    F.line = 158;
    r_p0.a0 = ((rotl__pureZrandom_u24(s0_771751975, 55n) ^ s1_771751976) ^ BigInt.asUintN(64, s1_771751976 << (BigInt(14) & 63n)));
    F.line = 159;
    r_p0.a1 = rotl__pureZrandom_u24(s1_771751976, 36n);
  framePtr = F.prev;

  return result_771751974;

}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function skipRandomNumbers__pureZrandom_u45(s_p0) {
  var F = {procname: "random.skipRandomNumbers", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
  framePtr = F;
    F.line = 218;
    F.filename = "random.nim";
    var s0_771751984 = 0n;
    F.line = 219;
    var s1_771751985 = 0n;
    Label1: {
      F.line = 220;
      var i_771751994 = 0;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_687867678 = 0;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_687867678 <= 1)) break Label3;
            F.line = 220;
            F.filename = "random.nim";
            i_771751994 = res_687867678;
            Label4: {
              F.line = 221;
              var b_771751999 = 0;
              F.line = 128;
              F.filename = "iterators_1.nim";
              var i_687867676 = 0;
              Label5: {
                F.line = 129;
                  Label6: while (true) {
                  if (!(i_687867676 < 64)) break Label6;
                    F.line = 221;
                    F.filename = "random.nim";
                    b_771751999 = i_687867676;
                    if (!(((helper_771751983[chckIndx(i_771751994, 0, (helper_771751983).length - 1)] & BigInt.asUintN(64, 1n << (BigInt(BigInt.asUintN(64, BigInt(b_771751999))) & 63n))) == 0n))) {
                    F.line = 223;
                    s0_771751984 = (s0_771751984 ^ s_p0.a0);
                    F.line = 224;
                    s1_771751985 = (s1_771751985 ^ s_p0.a1);
                    }
                    
                    F.line = 225;
                    (next__pureZrandom_u36(s_p0));
                    F.line = 131;
                    F.filename = "iterators_1.nim";
                    i_687867676 = addInt(i_687867676, 1);
                  }
              };
            };
            F.line = 102;
            res_687867678 = addInt(res_687867678, 1);
          }
      };
    };
    F.line = 226;
    F.filename = "random.nim";
    s_p0.a0 = s0_771751984;
    F.line = 227;
    s_p0.a1 = s1_771751985;
  framePtr = F.prev;

  
}

function initRand__pureZrandom_u250(seed_p0) {
    var Temporary1;

  var result_771752188 = [({a0: 0n, a1: 0n})];

  var F = {procname: "random.initRand", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
  framePtr = F;
    F.line = 606;
    F.filename = "random.nim";
    if (!((seed_p0 == 0n))) {
    Temporary1 = seed_p0;
    }
    else {
    Temporary1 = 2147483647n;
    }
    
    var seed_771752194 = Temporary1;
    F.line = 607;
    result_771752188[0] = nimCopy(result_771752188[0], {a0: BigInt.asUintN(64, (seed_771752194 >> (BigInt(16) & 63n))), a1: BigInt.asUintN(64, (seed_771752194 & 65535n))}, NTI771751940);
    F.line = 611;
    skipRandomNumbers__pureZrandom_u45(result_771752188[0]);
    F.line = 612;
    (next__pureZrandom_u36(result_771752188[0]));
  framePtr = F.prev;

  return result_771752188[0];

}

function initRand__pureZrandom_u292() {
  var result_771752229 = ({a0: 0n, a1: 0n});

  var F = {procname: "random.initRand", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
  framePtr = F;
    F.line = 698;
    F.filename = "random.nim";
    var time_771752230 = (chckRange(BigInt(Math.trunc((epochTime__pureZtimes_u4708() * 1000.0))), (-9223372036854775808n), 9223372036854775807n) & 2147483647n);
    F.line = 699;
    result_771752229 = nimCopy(result_771752229, initRand__pureZrandom_u250(time_771752230), NTI771751940);
  framePtr = F.prev;

  return result_771752229;

}

function randomize__pureZrandom_u299() {
  var F = {procname: "random.randomize", prev: framePtr, filename: "/usr/lib/nim/lib/pure/random.nim", line: 0};
  framePtr = F;
    F.line = 753;
    F.filename = "random.nim";
    state_771751951[0] = nimCopy(state_771751951[0], initRand__pureZrandom_u292(), NTI771751940);
  framePtr = F.prev;

  
}
var F = {procname: "module core", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
framePtr = F;
F.line = 3;
F.filename = "core.nim";
randomize__pureZrandom_u299();
F.line = 16;
var Unit_687865872 = {};
framePtr = F.prev;
var F = {procname: "module core", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function String_count__core_u346(str_p0) {
  var result_687866204 = 0;

  var F = {procname: "core.String_count", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 250;
    F.filename = "core.nim";
    result_687866204 = (str_p0).length;
  framePtr = F.prev;

  return result_687866204;

}

function nucisCombining(c_p0) {
  var result_973079946 = false;

  var F = {procname: "unicode.isCombining", prev: framePtr, filename: "/usr/lib/nim/lib/pure/unicode.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 628;
    F.filename = "unicode.nim";
    var c_973079947 = c_p0;
    F.line = 631;
    result_973079946 = ((768 <= c_973079947) && (((((c_973079947 <= 879) || ((6832 <= c_973079947) && (c_973079947 <= 6911))) || ((7616 <= c_973079947) && (c_973079947 <= 7679))) || ((8400 <= c_973079947) && (c_973079947 <= 8447))) || ((65056 <= c_973079947) && (c_973079947 <= 65071))));
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_973079946;

}

function reversed__pureZunicode_u4844(s_p0) {
  var result_973083374 = [];

  var F = {procname: "unicode.reversed", prev: framePtr, filename: "/usr/lib/nim/lib/pure/unicode.nim", line: 0};
  framePtr = F;
    F.line = 877;
    F.filename = "unicode.nim";
    var i_973083375 = 0;
    F.line = 878;
    var lastI_973083376 = 0;
    F.line = 879;
    var newPos_973083380 = subInt((s_p0).length, 1);
    F.line = 880;
    var blockPos_973083381 = 0;
    F.line = 881;
    var r_973083382 = 0;
    F.line = 891;
    result_973083374 = nimCopy(null, mnewString(chckRange((s_p0).length, 0, 2147483647)), NTI33554449);
    Label1: {
      F.line = 893;
        Label2: while (true) {
        if (!(i_973083375 < (s_p0).length)) break Label2;
          F.line = 894;
          lastI_973083376 = i_973083375;
          if ((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] <= 127)) {
          F.line = 91;
          r_973083382 = chckRange(s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)], (-2147483648), 2147483647);
          F.line = 92;
          i_973083375 = addInt(i_973083375, 1);
          }
          else {
          if (((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] >>> (5 & 31)) == 6)) {
          if ((i_973083375 <= subInt((s_p0).length, 2))) {
          F.line = 96;
          r_973083382 = chckRange(((((((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] & 31) >>> 0) << (6 & 31)) >>> 0) | ((s_p0[chckIndx(addInt(i_973083375, 1), 0, (s_p0).length - 1)] & 63) >>> 0)) >>> 0), (-2147483648), 2147483647);
          F.line = 98;
          i_973083375 = addInt(i_973083375, 2);
          }
          else {
            F.line = 100;
            r_973083382 = 65533;
            F.line = 101;
            i_973083375 = addInt(i_973083375, 1);
          }
          
          }
          else {
          if (((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] >>> (4 & 31)) == 14)) {
          if ((i_973083375 <= subInt((s_p0).length, 3))) {
          F.line = 106;
          r_973083382 = chckRange(((((((((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] & 15) >>> 0) << (12 & 31)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 1), 0, (s_p0).length - 1)] & 63) >>> 0) << (6 & 31)) >>> 0)) >>> 0) | ((s_p0[chckIndx(addInt(i_973083375, 2), 0, (s_p0).length - 1)] & 63) >>> 0)) >>> 0), (-2147483648), 2147483647);
          F.line = 109;
          i_973083375 = addInt(i_973083375, 3);
          }
          else {
            F.line = 111;
            r_973083382 = 65533;
            F.line = 112;
            i_973083375 = addInt(i_973083375, 1);
          }
          
          }
          else {
          if (((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] >>> (3 & 31)) == 30)) {
          if ((i_973083375 <= subInt((s_p0).length, 4))) {
          F.line = 118;
          r_973083382 = chckRange(((((((((((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] & 7) >>> 0) << (18 & 31)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 1), 0, (s_p0).length - 1)] & 63) >>> 0) << (12 & 31)) >>> 0)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 2), 0, (s_p0).length - 1)] & 63) >>> 0) << (6 & 31)) >>> 0)) >>> 0) | ((s_p0[chckIndx(addInt(i_973083375, 3), 0, (s_p0).length - 1)] & 63) >>> 0)) >>> 0), (-2147483648), 2147483647);
          F.line = 122;
          i_973083375 = addInt(i_973083375, 4);
          }
          else {
            F.line = 124;
            r_973083382 = 65533;
            F.line = 125;
            i_973083375 = addInt(i_973083375, 1);
          }
          
          }
          else {
          if (((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] >>> (2 & 31)) == 62)) {
          if ((i_973083375 <= subInt((s_p0).length, 5))) {
          F.line = 132;
          r_973083382 = chckRange(((((((((((((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] & 3) >>> 0) << (24 & 31)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 1), 0, (s_p0).length - 1)] & 63) >>> 0) << (18 & 31)) >>> 0)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 2), 0, (s_p0).length - 1)] & 63) >>> 0) << (12 & 31)) >>> 0)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 3), 0, (s_p0).length - 1)] & 63) >>> 0) << (6 & 31)) >>> 0)) >>> 0) | ((s_p0[chckIndx(addInt(i_973083375, 4), 0, (s_p0).length - 1)] & 63) >>> 0)) >>> 0), (-2147483648), 2147483647);
          F.line = 137;
          i_973083375 = addInt(i_973083375, 5);
          }
          else {
            F.line = 139;
            r_973083382 = 65533;
            F.line = 140;
            i_973083375 = addInt(i_973083375, 1);
          }
          
          }
          else {
          if (((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] >>> (1 & 31)) == 126)) {
          if ((i_973083375 <= subInt((s_p0).length, 6))) {
          F.line = 148;
          r_973083382 = chckRange(((((((((((((((s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)] & 1) >>> 0) << (30 & 31)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 1), 0, (s_p0).length - 1)] & 63) >>> 0) << (24 & 31)) >>> 0)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 2), 0, (s_p0).length - 1)] & 63) >>> 0) << (18 & 31)) >>> 0)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 3), 0, (s_p0).length - 1)] & 63) >>> 0) << (12 & 31)) >>> 0)) >>> 0) | ((((s_p0[chckIndx(addInt(i_973083375, 4), 0, (s_p0).length - 1)] & 63) >>> 0) << (6 & 31)) >>> 0)) >>> 0) | ((s_p0[chckIndx(addInt(i_973083375, 5), 0, (s_p0).length - 1)] & 63) >>> 0)) >>> 0), (-2147483648), 2147483647);
          F.line = 154;
          i_973083375 = addInt(i_973083375, 6);
          }
          else {
            F.line = 156;
            r_973083382 = 65533;
            F.line = 157;
            i_973083375 = addInt(i_973083375, 1);
          }
          
          }
          else {
            F.line = 159;
            r_973083382 = chckRange(s_p0[chckIndx(i_973083375, 0, (s_p0).length - 1)], (-2147483648), 2147483647);
            F.line = 160;
            i_973083375 = addInt(i_973083375, 1);
          }
          }}}}}
          if (!(nucisCombining(r_973083382))) {
          F.line = 884;
          var jHEX60gensym554_973083629 = subInt(lastI_973083376, 1);
          Label3: {
            F.line = 885;
              Label4: while (true) {
              if (!(blockPos_973083381 < jHEX60gensym554_973083629)) break Label4;
                F.line = 886;
                result_973083374[chckIndx(newPos_973083380, 0, (result_973083374).length - 1)] = s_p0[chckIndx(jHEX60gensym554_973083629, 0, (s_p0).length - 1)];
                F.line = 887;
                jHEX60gensym554_973083629 = subInt(jHEX60gensym554_973083629, 1);
                F.line = 888;
                newPos_973083380 = subInt(newPos_973083380, 1);
              }
          };
          F.line = 889;
          blockPos_973083381 = subInt(lastI_973083376, 1);
          }
          
        }
    };
    F.line = 884;
    var jHEX60gensym557_973083644 = subInt((s_p0).length, 1);
    Label5: {
      F.line = 885;
        Label6: while (true) {
        if (!(blockPos_973083381 < jHEX60gensym557_973083644)) break Label6;
          F.line = 886;
          result_973083374[chckIndx(newPos_973083380, 0, (result_973083374).length - 1)] = s_p0[chckIndx(jHEX60gensym557_973083644, 0, (s_p0).length - 1)];
          F.line = 887;
          jHEX60gensym557_973083644 = subInt(jHEX60gensym557_973083644, 1);
          F.line = 888;
          newPos_973083380 = subInt(newPos_973083380, 1);
        }
    };
    F.line = 889;
    blockPos_973083381 = subInt((s_p0).length, 1);
  framePtr = F.prev;

  return result_973083374;

}

function reversed__pureZunicode_u7395(s_p0) {
  var result_973085925 = [];

  var F = {procname: "unicode.reversed", prev: framePtr, filename: "/usr/lib/nim/lib/pure/unicode.nim", line: 0};
  framePtr = F;
    F.line = 1396;
    F.filename = "unicode.nim";
    result_973085925 = nimCopy(null, reversed__pureZunicode_u4844((s_p0.slice(0, (s_p0).length - 1 + 1))), NTI33554449);
  framePtr = F.prev;

  return result_973085925;

}

function String_reversed__core_u343(str_p0) {
  var result_687866201 = [];

  var F = {procname: "core.String_reversed", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 247;
    F.filename = "core.nim";
    result_687866201 = nimCopy(null, reversed__pureZunicode_u7395(str_p0), NTI33554449);
  framePtr = F.prev;

  return result_687866201;

}

function nsuToLowerAsciiChar(c_p0) {
  var result_922746967 = 0;

  var F = {procname: "strutils.toLowerAscii", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    if ((ConstSet2[c_p0] != undefined)) {
    F.line = 219;
    F.filename = "strutils.nim";
    result_922746967 = (c_p0 ^ 32);
    }
    else {
      F.line = 221;
      result_922746967 = c_p0;
    }
    
  framePtr = F.prev;

  return result_922746967;

}

function nsuToLowerAsciiStr(s_p0) {
  var result_922746977 = [];

  var F = {procname: "strutils.toLowerAscii", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 224;
    F.filename = "strutils.nim";
    result_922746977 = nimCopy(null, mnewString(chckRange((s_p0).length, 0, 2147483647)), NTI33554449);
    Label1: {
      F.line = 225;
      var iHEX60gensym7_922746983 = 0;
      F.line = 81;
      F.filename = "iterators_1.nim";
      var colontmp__553648230 = 0;
      F.line = 225;
      F.filename = "strutils.nim";
      colontmp__553648230 = subInt((s_p0).length, 1);
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_553648231 = 0;
      Label2: {
        F.line = 97;
          Label3: while (true) {
          if (!(res_553648231 <= colontmp__553648230)) break Label3;
            F.line = 239;
            F.filename = "strutils.nim";
            iHEX60gensym7_922746983 = res_553648231;
            F.line = 226;
            result_922746977[chckIndx(iHEX60gensym7_922746983, 0, (result_922746977).length - 1)] = nsuToLowerAsciiChar(s_p0[chckIndx(iHEX60gensym7_922746983, 0, (s_p0).length - 1)]);
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_553648231 = addInt(res_553648231, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_922746977;

}

function String_lowercase__core_u370(str_p0) {
  var result_687866228 = [];

  var F = {procname: "core.String_lowercase", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 274;
    F.filename = "core.nim";
    result_687866228 = nimCopy(null, nsuToLowerAsciiStr(str_p0), NTI33554449);
  framePtr = F.prev;

  return result_687866228;

}

function substrEq__pureZstrutils_u256(s_p0, pos_p1, substr_p2) {
    var Temporary1;

  var result_922747140 = false;

  var F = {procname: "strutils.substrEq", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 371;
    F.filename = "strutils.nim";
    F.line = 371;
    var length_922747141 = (substr_p2).length;
    if ((0 < length_922747141)) {
    F.line = 373;
    var i_922747142 = 0;
    Label2: {
      F.line = 374;
        Label3: while (true) {
        if (!(((i_922747142 < length_922747141) && (addInt(pos_p1, i_922747142) < (s_p0).length)) && (s_p0[chckIndx(addInt(pos_p1, i_922747142), 0, (s_p0).length - 1)] == substr_p2[chckIndx(i_922747142, 0, (substr_p2).length - 1)]))) break Label3;
          F.line = 375;
          i_922747142 = addInt(i_922747142, 1);
        }
    };
    Temporary1 = (i_922747142 == length_922747141);
    }
    else {
    Temporary1 = false;
    }
    
    result_922747140 = Temporary1;
  framePtr = F.prev;

  return result_922747140;

}

function substr__system_u3759(s_p0, first_p1, last_p2) {
  var result_33558195 = [];

  var F = {procname: "system.substr", prev: framePtr, filename: "/usr/lib/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 2919;
    F.filename = "system.nim";
    var first_33558196 = nimMax(first_p1, 0);
    F.line = 2920;
    var last_33558197 = nimMin(last_p2, (s_p0).length - 1);
    F.line = 2921;
    var L_33558198 = nimMax(addInt(subInt(last_33558197, first_33558196), 1), 0);
    F.line = 2922;
    result_33558195 = nimCopy(null, mnewString(chckRange(L_33558198, 0, 2147483647)), NTI33554449);
    Label1: {
      F.line = 2927;
      var i_33558208 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_553648247 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_553648247 < L_33558198)) break Label3;
            F.line = 2927;
            F.filename = "system.nim";
            i_33558208 = i_553648247;
            F.line = 2928;
            result_33558195[chckIndx(i_33558208, 0, (result_33558195).length - 1)] = s_p0[chckIndx(addInt(i_33558208, first_33558196), 0, (s_p0).length - 1)];
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_553648247 = addInt(i_553648247, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_33558195;

}

function nsuSplitString(s_p0, sep_p1, maxsplit_p2) {
      var Temporary2;

  var result_922747459 = [];

  var F = {procname: "strutils.split", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 418;
    F.filename = "strutils.nim";
    result_922747459 = nimCopy(null, [], NTI922747294);
    Label1: {
      F.line = 419;
      var xHEX60gensym69_922747465 = [];
      F.line = 536;
      if (((sep_p1).length == 0)) {
      Temporary2 = 1;
      }
      else {
      Temporary2 = (sep_p1).length;
      }
      
      var sepLen_553648236 = Temporary2;
      F.line = 390;
      var lastHEX60gensym41_553648237 = 0;
      F.line = 391;
      var splitsHEX60gensym41_553648238 = maxsplit_p2;
      Label3: {
        F.line = 538;
          Label4: while (true) {
          if (!(lastHEX60gensym41_553648237 <= (s_p0).length)) break Label4;
            F.line = 394;
            var firstHEX60gensym41_553648240 = lastHEX60gensym41_553648237;
            Label5: {
              F.line = 395;
                Label6: while (true) {
                if (!((lastHEX60gensym41_553648237 < (s_p0).length) && !(substrEq__pureZstrutils_u256(s_p0, lastHEX60gensym41_553648237, sep_p1)))) break Label6;
                  F.line = 396;
                  lastHEX60gensym41_553648237 = addInt(lastHEX60gensym41_553648237, 1);
                }
            };
            if ((splitsHEX60gensym41_553648238 == 0)) {
            F.line = 397;
            lastHEX60gensym41_553648237 = (s_p0).length;
            }
            
            F.line = 804;
            xHEX60gensym69_922747465 = substr__system_u3759(s_p0, firstHEX60gensym41_553648240, subInt(lastHEX60gensym41_553648237, 1));
            F.line = 419;
            var Temporary7 = nimCopy(null, xHEX60gensym69_922747465, NTI33554449);
            result_922747459.push(Temporary7);;
            if ((splitsHEX60gensym41_553648238 == 0)) {
            F.line = 399;
            break Label3;
            }
            
            F.line = 400;
            splitsHEX60gensym41_553648238 = subInt(splitsHEX60gensym41_553648238, 1);
            F.line = 401;
            lastHEX60gensym41_553648237 = addInt(lastHEX60gensym41_553648237, sepLen_553648236);
          }
      };
    };
  framePtr = F.prev;

  return result_922747459;

}

function String_split__core_u387(str_p0, delimiter_p1) {
  var result_687866246 = [];

  var F = {procname: "core.String_split", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 295;
    F.filename = "core.nim";
    result_687866246 = nimCopy(null, nsuSplitString(str_p0, delimiter_p1, (-1)), NTI922747294);
  framePtr = F.prev;

  return result_687866246;

}

function sysFatal__stdZassertions_u46(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/usr/lib/nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 62;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u44(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/usr/lib/nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 40;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u46(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u86(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/usr/lib/nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 45;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u44(msg_p0);
  framePtr = F.prev;

  
}

function String_forEach__core_u535(str_p0, fn_p1) {
  var F = {procname: "core.String_forEach", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    Label1: {
      F.line = 338;
      F.filename = "core.nim";
      var ch_687866396 = 0;
      F.line = 267;
      F.filename = "iterators.nim";
      var i_553648250 = 0;
      F.line = 268;
      var L_553648251 = (str_p0).length;
      Label2: {
        F.line = 269;
          Label3: while (true) {
          if (!(i_553648250 < L_553648251)) break Label3;
            F.line = 338;
            F.filename = "core.nim";
            ch_687866396 = str_p0[chckIndx(i_553648250, 0, (str_p0).length - 1)];
            F.line = 339;
            fn_p1(ch_687866396);
            F.line = 13;
            F.filename = "iterators.nim";
            i_553648250 += 1;
            if (!(((str_p0).length == L_553648251))) {
            F.line = 272;
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("/usr/lib/nim/lib/system/iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  
}

function Any_toString__testss_u7(value_p0, indent_p1) {
  var result_553648139 = [];

  var F = {procname: "Any_toString.Any_toString", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 238;
    F.filename = "core.nim";
    result_553648139 = nimCopy(null, nimCharToStr(value_p0), NTI33554449);
  framePtr = F.prev;

  return result_553648139;

}

function Any_echo__testss_u4(obj_p0) {
  var F = {procname: "Any_echo.Any_echo", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 241;
    F.filename = "core.nim";
    rawEcho(Any_toString__testss_u7(obj_p0, 0));
  framePtr = F.prev;

  
}

function String_filter__core_u541(str_p0, predicate_p1) {
  var result_687866402 = [];

  var F = {procname: "core.String_filter", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 342;
    F.filename = "core.nim";
    F.line = 342;
    var buf_687866403 = mnewString(0);
    Label1: {
      F.line = 343;
      var ch_687866404 = 0;
      F.line = 267;
      F.filename = "iterators.nim";
      var i_553648254 = 0;
      F.line = 268;
      var L_553648255 = (str_p0).length;
      Label2: {
        F.line = 269;
          Label3: while (true) {
          if (!(i_553648254 < L_553648255)) break Label3;
            F.line = 343;
            F.filename = "core.nim";
            ch_687866404 = str_p0[chckIndx(i_553648254, 0, (str_p0).length - 1)];
            if (predicate_p1(ch_687866404)) {
            F.line = 345;
            addChar(buf_687866403, ch_687866404);;
            }
            
            F.line = 13;
            F.filename = "iterators.nim";
            i_553648254 += 1;
            if (!(((str_p0).length == L_553648255))) {
            F.line = 272;
            failedAssertImpl__stdZassertions_u86(makeNimstrLit("/usr/lib/nim/lib/system/iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it"));
            }
            
          }
      };
    };
    result_687866402 = nimCopy(null, buf_687866403, NTI33554449);
  framePtr = F.prev;

  return result_687866402;

}

function nsuFindChar(s_p0, sub_p1, start_p2, last_p3) {
    var Temporary1;

  var result_922748584 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1972;
    F.filename = "strutils.nim";
    result_922748584 = (-1);
    F.line = 1973;
    if ((last_p3 < 0)) {
    Temporary1 = (s_p0).length - 1;
    }
    else {
    Temporary1 = last_p3;
    }
    
    var last_922748585 = Temporary1;
    Label2: {
      F.line = 1976;
      var iHEX60gensym174_922748599 = 0;
      F.line = 81;
      F.filename = "iterators_1.nim";
      var colontmp__553648264 = 0;
      F.line = 1976;
      F.filename = "strutils.nim";
      colontmp__553648264 = start_p2;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_553648265 = colontmp__553648264;
      Label3: {
        F.line = 97;
          Label4: while (true) {
          if (!(res_553648265 <= last_922748585)) break Label4;
            F.line = 1990;
            F.filename = "strutils.nim";
            iHEX60gensym174_922748599 = res_553648265;
            if ((s_p0[chckIndx(iHEX60gensym174_922748599, 0, (s_p0).length - 1)] == sub_p1)) {
            F.line = 1978;
            result_922748584 = iHEX60gensym174_922748599;
            break BeforeRet;
            }
            
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_553648265 = addInt(res_553648265, 1);
          }
      };
    };
  };
  framePtr = F.prev;

  return result_922748584;

}

function substr__system_u3777(s_p0, first_p1) {
  var result_33558212 = [];

  var F = {procname: "system.substr", prev: framePtr, filename: "/usr/lib/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 2931;
    F.filename = "system.nim";
    result_33558212 = nimCopy(null, substr__system_u3759(s_p0, first_p1, (s_p0).length - 1), NTI33554449);
  framePtr = F.prev;

  return result_33558212;

}

function fill__pureZstrutils_u1623(a_p0, value_p1) {
  var F = {procname: "fill.fill", prev: framePtr, filename: "/usr/lib/nim/lib/pure/algorithm.nim", line: 0};
  framePtr = F;
    F.line = 72;
    F.filename = "algorithm.nim";
    var xHEX60gensym170_922748512 = 0;
    Label1: {
      F.line = 98;
        Label2: while (true) {
        if (!(xHEX60gensym170_922748512 <= (a_p0).length - 1)) break Label2;
          F.line = 98;
          a_p0[chckIndx(xHEX60gensym170_922748512, 0, (a_p0).length - 1)] = value_p1;
          F.line = 75;
          xHEX60gensym170_922748512 = addInt(xHEX60gensym170_922748512, 1);
        }
    };
  framePtr = F.prev;

  
}

function nsuInitSkipTable(a_p0, sub_p1) {
  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1905;
    F.filename = "strutils.nim";
    var m_922748502 = (sub_p1).length;
    F.line = 1906;
    fill__pureZstrutils_u1623(a_p0, m_922748502);
    Label1: {
      F.line = 1908;
      var i_922748522 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__553648268 = 0;
      F.line = 1908;
      F.filename = "strutils.nim";
      colontmp__553648268 = subInt(m_922748502, 1);
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_553648269 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_553648269 < colontmp__553648268)) break Label3;
            F.line = 1908;
            F.filename = "strutils.nim";
            i_922748522 = i_553648269;
            F.line = 1909;
            a_p0[chckIndx(sub_p1[chckIndx(i_922748522, 0, (sub_p1).length - 1)], 0, (a_p0).length - 1)] = subInt(subInt(m_922748502, 1), i_922748522);
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_553648269 = addInt(i_553648269, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function nsuInitNewSkipTable(sub_p0) {
  var result_922748556 = [new Int32Array(256)];

  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1918;
    F.filename = "strutils.nim";
    nsuInitSkipTable(result_922748556[0], sub_p0);
  framePtr = F.prev;

  return result_922748556[0];

}

function nsuFindStrA(a_p0, s_p1, sub_p2, start_p3, last_p4) {
    var Temporary1;

  var result_922748563 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1932;
    F.filename = "strutils.nim";
    if ((last_p4 < 0)) {
    Temporary1 = (s_p1).length - 1;
    }
    else {
    Temporary1 = last_p4;
    }
    
    var last_922748564 = Temporary1;
    F.line = 1933;
    var subLast_922748565 = subInt((sub_p2).length, 1);
    if ((subLast_922748565 == (-1))) {
    F.line = 1938;
    result_922748563 = start_p3;
    break BeforeRet;
    }
    
    F.line = 1942;
    result_922748563 = (-1);
    F.line = 1943;
    var skip_922748566 = start_p3;
    Label2: {
      F.line = 1945;
        Label3: while (true) {
        if (!(subLast_922748565 <= subInt(last_922748564, skip_922748566))) break Label3;
          F.line = 1946;
          var i_922748567 = subLast_922748565;
          Label4: {
            F.line = 1947;
              Label5: while (true) {
              if (!(s_p1[chckIndx(addInt(skip_922748566, i_922748567), 0, (s_p1).length - 1)] == sub_p2[chckIndx(i_922748567, 0, (sub_p2).length - 1)])) break Label5;
                if ((i_922748567 == 0)) {
                F.line = 1949;
                result_922748563 = skip_922748566;
                break BeforeRet;
                }
                
                F.line = 1950;
                i_922748567 = subInt(i_922748567, 1);
              }
          };
          F.line = 1951;
          skip_922748566 = addInt(skip_922748566, a_p0[chckIndx(s_p1[chckIndx(addInt(skip_922748566, subLast_922748565), 0, (s_p1).length - 1)], 0, (a_p0).length - 1)]);
        }
    };
  };
  framePtr = F.prev;

  return result_922748563;

}

function nsuReplaceStr(s_p0, sub_p1, by_p2) {
  var result_922748771 = [];

  var F = {procname: "strutils.replace", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 2210;
    F.filename = "strutils.nim";
    result_922748771 = nimCopy(null, [], NTI33554449);
    F.line = 2211;
    var subLen_922748772 = (sub_p1).length;
    if ((subLen_922748772 == 0)) {
    F.line = 2213;
    result_922748771 = nimCopy(null, s_p0, NTI33554449);
    }
    else {
    if ((subLen_922748772 == 1)) {
    F.line = 2217;
    var c_922748773 = sub_p1[chckIndx(0, 0, (sub_p1).length - 1)];
    F.line = 2218;
    var last_922748774 = (s_p0).length - 1;
    F.line = 2219;
    var i_922748775 = 0;
    Label1: {
      F.line = 2220;
        Label2: while (true) {
        if (!true) break Label2;
          F.line = 2221;
          var j_922748776 = nsuFindChar(s_p0, c_922748773, chckRange(i_922748775, 0, 2147483647), last_922748774);
          if ((j_922748776 < 0)) {
          F.line = 2222;
          break Label1;
          }
          
          F.line = 2223;
          nimAddStrStr(result_922748771, substr__system_u3759(s_p0, i_922748775, subInt(j_922748776, 1)));;
          F.line = 2224;
          nimAddStrStr(result_922748771, by_p2);;
          F.line = 2225;
          i_922748775 = addInt(j_922748776, subLen_922748772);
        }
    };
    F.line = 2227;
    nimAddStrStr(result_922748771, substr__system_u3777(s_p0, i_922748775));;
    }
    else {
      F.line = 2229;
      var a_922748777 = nsuInitNewSkipTable(sub_p1);
      F.line = 2230;
      var last_922748778 = (s_p0).length - 1;
      F.line = 2231;
      var i_922748779 = 0;
      Label3: {
        F.line = 2232;
          Label4: while (true) {
          if (!true) break Label4;
            F.line = 2233;
            var j_922748780 = nsuFindStrA(a_922748777, s_p0, sub_p1, chckRange(i_922748779, 0, 2147483647), last_922748778);
            if ((j_922748780 < 0)) {
            F.line = 2234;
            break Label3;
            }
            
            F.line = 2235;
            nimAddStrStr(result_922748771, substr__system_u3759(s_p0, i_922748779, subInt(j_922748780, 1)));;
            F.line = 2236;
            nimAddStrStr(result_922748771, by_p2);;
            F.line = 2237;
            i_922748779 = addInt(j_922748780, subLen_922748772);
          }
      };
      F.line = 2239;
      nimAddStrStr(result_922748771, substr__system_u3777(s_p0, i_922748779));;
    }
    }
  framePtr = F.prev;

  return result_922748771;

}

function String_replace_with__core_u511(str_p0, oldVal_p1, newVal_p2) {
  var result_687866371 = [];

  var F = {procname: "core.String_replace_with", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 323;
    F.filename = "core.nim";
    result_687866371 = nimCopy(null, nsuReplaceStr(str_p0, oldVal_p1, newVal_p2), NTI33554449);
  framePtr = F.prev;

  return result_687866371;

}

function nsuFindStr(s_p0, sub_p1, start_p2, last_p3) {
  var result_922748621 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((subInt((s_p0).length, start_p2) < (sub_p1).length)) {
    F.line = 2032;
    F.filename = "strutils.nim";
    result_922748621 = (-1);
    break BeforeRet;
    }
    
    if (((sub_p1).length == 1)) {
    F.line = 2033;
    result_922748621 = nsuFindChar(s_p0, sub_p1[chckIndx(0, 0, (sub_p1).length - 1)], start_p2, last_p3);
    break BeforeRet;
    }
    
    F.line = 2036;
    result_922748621 = nsuFindStrA(nsuInitNewSkipTable(sub_p1), s_p0, sub_p1, start_p2, last_p3);
  };
  framePtr = F.prev;

  return result_922748621;

}

function contains__pureZstrutils_u1879(s_p0, sub_p1) {
  var result_922748762 = false;

  var F = {procname: "strutils.contains", prev: framePtr, filename: "/usr/lib/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 2190;
    F.filename = "strutils.nim";
    result_922748762 = (0 <= nsuFindStr(s_p0, sub_p1, 0, (-1)));
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_922748762;

}

function String_contains__core_u507(str_p0, substring_p1) {
  var result_687866366 = false;

  var F = {procname: "core.String_contains", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/core.nim", line: 0};
  framePtr = F;
    F.line = 320;
    F.filename = "core.nim";
    result_687866366 = contains__pureZstrutils_u1879(str_p0, substring_p1);
  framePtr = F.prev;

  return result_687866366;

}
var Temporary2;

function HEX3Aanonymous__testss_u2(char_p0) {
  var F = {procname: "testss.:anonymous", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/testss.nim", line: 0};
  framePtr = F;
    F.line = 10;
    F.filename = "testss.nim";
    Any_echo__testss_u4(char_p0);
  framePtr = F.prev;

  
}
var Temporary3;

function HEX3Aanonymous__testss_u33(it_p0) {
  var result_553648163 = false;

  var F = {procname: "testss.:anonymous", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/testss.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 12;
    F.filename = "testss.nim";
    result_553648163 = (it_p0 == 98);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_553648163;

}
var F = {procname: "module testss", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/testss.nim", line: 0};
framePtr = F;
F.line = 3;
F.filename = "testss.nim";
(String_count__core_u346([102,111,111,45,98,97,114]));
F.line = 4;
(String_reversed__core_u343([100,114,97,119,101,114]));
F.line = 5;
(String_lowercase__core_u370([66,65,79,66,65,66]));
F.line = 8;
(String_split__core_u387([102,111,111,45,98,97,114], [45]));
F.line = 9;
Temporary2 = HEX3Aanonymous__testss_u2.bind(null); Temporary2.ClP_0 = HEX3Aanonymous__testss_u2; Temporary2.ClE_0 = null;
String_forEach__core_u535([97,98,99,100,101,102], Temporary2);
F.line = 11;
Temporary3 = HEX3Aanonymous__testss_u33.bind(null); Temporary3.ClP_0 = HEX3Aanonymous__testss_u33; Temporary3.ClE_0 = null;
(String_filter__core_u541([98,97,111,98,97,98], Temporary3));
F.line = 13;
(String_replace_with__core_u511([102,111,111,45,98,97,114,45,98,97,122], [45], [32]));
F.line = 14;
(String_contains__core_u507([99,104,111,99,111,108,97,116,101], [108,97,116,101]));
framePtr = F.prev;
var F = {procname: "module testss", prev: framePtr, filename: "/home/gavr/Documents/Fun/Kotlin/Niva/Niva/NivaInNiva/.niva_nim/testss.nim", line: 0};
framePtr = F;
framePtr = F.prev;
